replicaCount: 1

image:
  backend:
    repository: "prashantt597/backend"
    pullPolicy: Always
    tag: "latest"
  frontend:
    repository: "prashantt597/frontend"
    pullPolicy: Always
    tag: "latest"

mysql:
  image:
    repository: "mysql"
    tag: "8.0"
  rootPassword: "password"
  database: "appdb"

service:
  backend:
    port: 3000
  frontend:
    port: 80

ingress:
  enabled: true
  host: "localhost"
  annotations: {}
