name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        run: |
          - run: az aks get-credentials --resource-group rg-github --name aks-github --overwrite-existing


      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install myapp ./helm --set image.repository=ghcr.io/${{ github.repository }}/backend --set image.tag=latest
