name: CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.29.0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        run: az aks get-credentials --name aks-cluster --resource-group aks-rg --overwrite-existing

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Deploy to AKS via Helm
        run: |
          helm upgrade --install app ./helm-chart --namespace default --create-namespace

      - name: Verify Deployment
        run: kubectl rollout status deployment/app
