name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up kubectl
        uses: azure/aks-set-context@v3
        with:
          resource-group: myResourceGroup
          cluster-name: myAKSCluster

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Deploy via Helm
        run: |
          helm upgrade --install myapp ./helm/myapp \
            --set image.repository=prashant0597/myapp \
            --set image.tag=latest
