name: CD - Deploy to AKS

on:
  workflow_run:
    workflows: ["CI - Node.js Build & Scan"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: AKS Credentials
        uses: azure/aks-set-context@v3
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          resource-group: rg-aks-github
          cluster-name: aks-github

      - name: Deploy using Helm
        run: |
          helm upgrade --install myapp ./helm/ \
            --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/myapp \
            --set image.tag=latest